import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { DashboardProvider } from '@/context/dashboard-Context'
import { ProfessionalsProvider } from '@/context/professionals-context'
import { ScheduleProvider } from '@/context/schedules-context'
import { ServiceProvider } from '@/context/services-context'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'RESERVAYA',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DashboardProvider>
          <ServiceProvider>
            <ProfessionalsProvider>
              <ScheduleProvider>{children}</ScheduleProvider>
            </ProfessionalsProvider>
          </ServiceProvider>
        </DashboardProvider>
      </body>
    </html>
  )
}
